name: btsa
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.7
  - pip
  - fbprophet==0.7.1
  - jupyter==1.0.0
  - jupyterlab==2.2.8
  - matplotlib==3.3.1
  - nb_conda_kernels
  - numpy==1.19.2
  - pandas==1.1.3
  - plotly==4.11.0
  - pymc3==3.9.3
  - scikit-learn==0.23.2
  - scipy==1.5.2
  - seaborn==0.11.0
  - statsmodels==0.12.0
  - pip:
    - gluonts==0.5.2
    - mxnet==1.7.0.post1
    - numpyro==0.4.0
    - sktime==0.4.2
    - tensorflow==2.3.1
    - tensorflow-probability==0.11.1
    - torch==1.6.0
    - pytorchts==0.2.0
    - ipywidgets==7.5.1
    - tb-nightly==2.4.0a20201007